name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install build tools
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Build
      run: make

    - name: Run basic test
      run: ./main

    - name: Run error test
      run: INVALID_FIRST_COMMAND=1 ./main || true

    - name: Perf smoke test
      run: env PERF_CHILDREN=3 ./main
